services:

  backend:
    build: ./backend
    container_name: weather_backend
    ports:
      - "10000:10000"

  frontend:
    build: ./Frontend
    container_name: weather_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:10000/predict
    depends_on:
      - backend