version: '3.9'

services:

  backend:
    build: ./backend
    container_name: weather_backend
    ports:
      - "10000:10000"

  frontend:
    build: ./Frontend
    container_name: weather_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend